name: Bug Report
description: Report a bug or issue with DuraPing
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue. Please fill out the information below to help us diagnose the problem.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: The mod crashes when...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Launch Minecraft with DuraPing installed
        2. Equip a diamond pickaxe
        3. Mine blocks until durability is low
        4. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: The mod should alert when durability is low
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: The game crashes / no alert appears / etc.
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      placeholder: "1.21.9"
    validations:
      required: true

  - type: input
    id: duraping-version
    attributes:
      label: DuraPing Version
      description: What version of DuraPing are you using?
      placeholder: "0.3.1"
    validations:
      required: true

  - type: input
    id: fabric-loader
    attributes:
      label: Fabric Loader Version
      description: What version of Fabric Loader are you using?
      placeholder: "0.17.3"
    validations:
      required: true

  - type: input
    id: fabric-api
    attributes:
      label: Fabric API Version
      description: What version of Fabric API are you using?
      placeholder: "0.134.0+1.21.9"
    validations:
      required: true

  - type: textarea
    id: other-mods
    attributes:
      label: Other Mods Installed
      description: List any other mods you have installed. This helps identify conflicts.
      placeholder: |
        - Mod Menu 11.0.0
        - Sodium 0.6.0
        - Iris Shaders 1.8.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs and Crash Reports
      description: |
        Please attach relevant logs or crash reports. You can find these in:
        - `.minecraft/logs/latest.log`
        - `.minecraft/crash-reports/`
        
        Drag and drop files here, or use a paste service like https://mclo.gs/
      placeholder: Paste logs or crash report link here
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: If relevant, paste your `config/duraping.json` file contents
      placeholder: Paste config file contents here
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Game Environment
      description: Where does this issue occur?
      options:
        - Singleplayer
        - Multiplayer (vanilla server)
        - Multiplayer (modded server)
        - Both singleplayer and multiplayer
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be relevant (screenshots, videos, etc.)
    validations:
      required: false

