blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/redlynxlabs/duraping/wiki
    about: Read the full documentation and setup guide
  - name: RedLynx Labs
    url: https://redlynx.io
    about: Visit our organization homepage

