name: Question or Support
description: Ask a question or get help using DuraPing
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using DuraPing? Ask away!
        
        Before submitting, please check:
        - [README documentation](https://github.com/redlynxlabs/duraping/blob/main/README.md)
        - [Existing issues](https://github.com/redlynxlabs/duraping/issues)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I... / Does DuraPing support... / Why does...
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Question Topic
      description: What is your question about?
      options:
        - Installation and setup
        - Configuration and settings
        - Alert types and thresholds
        - Compatibility with other mods
        - Keybindings and controls
        - Performance or technical details
        - Mod Menu integration
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Provide any relevant details about your setup:
        - Minecraft version
        - DuraPing version
        - Other mods installed
        - What you've already tried
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Current Configuration
      description: If relevant, paste your current config or settings
      placeholder: Paste config here if applicable
    validations:
      required: false

