modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "GPL-3.0"

[[mods]]
modId = "duraping"
version = "${version}"
displayName = "DuraPing"
description = '''
Lightweight durability alerts with sound/chat/toast/flash. Client-only QoL.
'''
authors = "RedLynx Labs, redkey"
displayURL = "https://redlynx.io"
logoFile = "logo.png"

[[dependencies.duraping]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.duraping]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"
