modLoader="neoforge"
loaderVersion="[4,)"

[[mods]]
modId="duraping"
version="${version}"
displayName="${mod_name}"
description="${description}"
authors="${mod_author}"
credits="${credits}"
logoFile="assets/duraping/icon.png"
updateJSONURL="https://github.com/${github_repo}/releases/latest/download/update.json"

[[dependencies.duraping]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.duraping]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version_range})"
ordering="NONE"
side="BOTH"

[[dependencies.duraping]]
modId="cloth-config"
mandatory=true
versionRange="[15.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.duraping]]
modId="modmenu"
mandatory=false
versionRange="[11.0.0,)"
ordering="NONE"
side="CLIENT"
