name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew --no-daemon build
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: duraping-build
          path: build/libs/*.jar

